### ISSUE TITLE
regex matching seemingly not working

### ISSUE THREAD

**Issue by colinricardo** [datacamp/sqlwhat#100]
Am I doing something wrong? 

See screenshot below:
<img width="1440" alt="screen shot 2017-05-26 at 4 24 43 am" src="https://cloud.githubusercontent.com/assets/21294951/26486953/47c857b6-41cb-11e7-855e-8d8917209ab4.png">

Test is on line `1071`, and works fine when `fixed=True` but I want to check for `and|AND`.

Another example is here: 
<img width="1440" alt="screen shot 2017-05-26 at 5 12 10 am" src="https://cloud.githubusercontent.com/assets/21294951/26488565/ed0fc7b2-41d1-11e7-982a-b800053908e0.png">

**Comment by machow** [comment]
@colinricardo ah, it's a bug. sqlwhat was trying to match regex expressions to beginning of string. I'll push the fix today.

**Comment by filipsch** [comment]
Fixed.
