### ISSUE TITLE
using digits=n causes error / question

### ISSUE THREAD

**Issue by colinricardo** [datacamp/sqlwhat#106]
### Outline
When using `digits=` kwarg of `test_column()` I get the following error:
<img width="1440" alt="screen shot 2017-06-06 at 11 16 05 am" src="https://user-images.githubusercontent.com/21294951/26836768-b8499e5a-4aa9-11e7-885c-c3385b5d65be.png">

SCT works fine when `digits=2` is removed. 

Am I doing something wrong?

**Comment by machow** [comment]
Shoot--no, this is a bug. In python, NULL values in the results are converted to None. But this throws an error when passed to the `round` function.

For context on the error message, in python the `round` function is just a fancy way of calling an object's [`__round__` method](https://docs.python.org/3/library/functions.html#round).

**Comment by machow** [comment]
fix is live!
