### ISSUE TITLE
Implement basic messaging system

### ISSUE THREAD

**Issue by machow** [datacamp/sqlwhat#34]
* generic pattern for AST libraries to report human friendly name of AstNode instances
* sqlwhat only uses most recent message for now, relies on highlighting for context. (e.g. rather than "Check the 1st Select statement. Check the WHERE clause. Did you _____?", Use highlighting + "Did you ____?".
* sqlwhat uses human friendly names when can't find node or field (e.g. "Did you define a {ordinal} {node_name}" -> "Did you define a 2nd SELECT statement?")

**Comment by machow** [comment]
Note, there is a working implementation on 

https://github.com/datacamp/sqlwhat/tree/feature-speaker

**Comment by machow** [comment]
The current messaging works by reporting a name for whatever node you're looking at. E.g.

"Check your `SELECT` statement"

This means that when you get the `WHERE` field of a `SELECT` statement, it will report whatever node is in that field. For example in 

`SELECT id FROM b WHERE id < 10`, it will say something like...

"Check the binary expression `<`".

Let me know if this isn't ideal, since an alternative is that it would say the field you are checking, rather than the node it contains.

"Check the `WHERE` clause of your `SELECT` statement."

**Comment by filipsch** [comment]
cc @colinricardo cc @ncarchedi

**Comment by colinricardo** [comment]
@machow I think saying the field rather than the node is a bit more informative. Can they be combined? e.g. 'Check the binary expression `<` in the `WHERE` clause of your `SELECT` statement?

**Comment by machow** [comment]
> Can they be combined?

Yes! That's a great suggestion--I was trying to keep it as simple as possible, but that seems like the most useful default.
