### ISSUE TITLE
Provide option in check_result to make case-insenstive

### ISSUE THREAD

**Issue by filipsch** [datacamp/sqlwhat#78]
Feedback from Graeme, Microsoft contact for the transact-sql course:

> Also, I noticed that I get an error based on the column name case not matching the expected answer (e.g. if I were to use the alias CustomerName when it expects Customername) – by default , Transact-SQL is case-insensitive so this should not cause an error. Can you fix that?

I suggest we put an option in `check_result()` and `test_column()` to be forgiving for case sensitivity. Pretty urgent.

**Comment by machow** [comment]
Closing, since in prod. Issue on how to handle to cleanup in case it should be handled differently with postgres here:

#85
