### ISSUE TITLE
question about check_field with DISTINCT

### ISSUE THREAD

**Issue by colinricardo** [datacamp/sqlwhat#99]
### Query
```
SELECT DISTINCT country
FROM films;
```

### SCT
```
distinct = sel.check_field('pref').has_equal_ast(msg='blah')
```

### sqlwhat-viewer
<img width="520" alt="screen shot 2017-05-26 at 2 04 32 am" src="https://cloud.githubusercontent.com/assets/21294951/26482923/156b49f8-41b8-11e7-9ba9-9a07ef928c81.png">

### Error
<img width="387" alt="screen shot 2017-05-26 at 2 04 43 am" src="https://cloud.githubusercontent.com/assets/21294951/26482925/1ae0ad56-41b8-11e7-8c81-816104f47c26.png">

### Question
Has the field for `DISTINCT` changed to something else?

cc @ncarchedi

**Comment by machow** [comment]
removed sqlwhat staging from the intro sql course. Wasn't able to replicate on current working branches, so maybe it was broken and fixed along the way?
